---
title: "GeRgraphy"
author: "Dave Evans and Aaron Ruesch"
date: "16 March, 2016"
output: ioslides_presentation
---
# Introduction

## Geographic Information Systems and Spatial Data
<div class="notes">
GIS stands for Geographic Information Systems, and is the term used for the dicipline and practice of incorporating, storing, manipulating, maintaining, analyzing, and displaying spatial data. GIS can be conceptualized as a suite of tools for working with spatial data. Spatial data are data that are referenced to a location, that is the data have coordinates that pin it down to a location on the Earth. Examples are so myriad as to almost not be useful, e.g. restaurant location, streets, geologic strata, and precipitation, but they all have in common numeric values that reference the location of the data in X and Y (or longitude and latitude). EXPLANATION OF X AND Y.

Arguably, the most common use of spatial data, and therefore GIS, are in data exploration, simply taking a look at where the phenomenon occur. This is useful in the sense that we can see obvious trends in the data, giving clues for further analysis, or merely checking our work, seeing if we have made mistakes. Additionally, spatial data is used for different kinds of analysis, leveraging the location data to make inferences. This analysis could take the form of selecting all wells that fall within certain soil types or in the construction of error terms in construction a statistical model. 

*Maybe delete this paragraph...*
The most common software used in GIS are ArcGIS, produced by ESRI and QGIS, an open source analog, but there are many other software packages for GIS, both propietary and open-source. Any familiarity with the most popular GISs will show you that they are GUI-based and therefore much different from the look and feel of R, and, while R is not necessarily a replacement for the ArcGIS or QGIS, the analysis and plotting capability of R makes it a powerful GIS, and when it comes to model construction, R, and no suprise here, blows the common GIS platforms out of the water.
</div>
## Spatial data types
<div class="notes">
*Maybe break this apart and put this into the respective intros of the datatypes below?*
Spatial data are divided up into two kinds of data, vector data and raster data. Vector data consist of the location data being defined by points. There are three main kinds of vector data: points, lines and polygons. Point data, as might be guessed, are data where each observation is defined by one coordinate pair, X and Y. In line data each observation is defined by a series of coordinate pairs that define a one dimensional path in space. Polygons are data where each observation is defined by coordinate pairs that trace out a two-dimensional area. Common uses of vector data are for phenomenon that have discrete boundaries and locations, e.g., wells and bird sitings for points, rivers and streets (at certain scales) for lines, and county borders and soil types for polygon data. Raster data are constructed as grids that are laid out over an area. Each cell of the grid contains some information about the phenomenon, but each cell will not be explicitly given a coordinate pair, rather every cell has the same length and width and so only the certain corners of the data need to be given coordinate pairs. Precipitation and temperature data are often portrayed as raster data because of the way they vary continuously over the space. Examples of the creation, input, and output of these data types are given below.

*Note to power users:*
The usual definitions of these data describe vector data as being for data with discrete boundaries and raster data for that which continuously varies. While this is true in general, it is essentially a matter of convenience that determines which type is best. For example, you could represent a dataset of bird sitings in a raster format, but because the grid is so sparse (NA or 'no siting' for nearly all the cells) it saves memory (and makes more inuitive sense) to store the data as points. Conversely, rainfall data can be stored as thousands of points, each marking the estimated rainfall at that location, but storing the data in this format is rather cumbersome if the area is large. 

This presentation is meant to give an introduction to handling spatial data in R. It's intended audience are those with at least a basic knowledge of R and an interest in, though not necessarily knowledge of, working with spatial data. We will cover basic handling and manipulation of vector data and raster data, and then give a flyover of how coordinate reference systems work and how to work with them in R.
</div>
## Other Resources
<div class="notes">
There are many other resources for using R for spatial data analysis and rather that reinvent the wheel we point you to a StackOverflow question: http://gis.stackexchange.com/questions/45327/tutorials-to-handle-spatial-data-in-r.
</div>


# Vector Data
<div class="notes">
The backbone of R's vector data utilities can be found in the packages 'sp', 'rgeos', and rgdal, with a lot of helpful tools being found in classInt, maptools, and many others. This presentation explore R's functionality with vector data, we will examine two different datasets: a set of wards with census data and election results, and polygons of soil types. (See the workspace directory for how these were put together.)
</div>
## Intro
<div class="notes">
Before the R stuff, the GIS stuff. Vector data can be easily described as shapes, and as we said they fall into three main categories, points lines and polygons. Most often, data are pacakged in collections, so we may have 72 polygons for the state of Wisconsin. Each of the counties (each shape) are referred to as a *feature*; this is a general rule about spatial data, each observation in the group is known as a feature. Each feature will have other data attached to it, these are known as *attributes* (for the entire dataset this often called the *attribute table*). As an example, the attributes of a soils dataset will decribe the sand and clay percentage for each polygon or for ward data they may hold the population information. 
</div>
## Input/Output
<div class="notes">
To read in the data we'll use the rgdal package (which is the R implentation of the GDAL suite of tools). Our data is in the form of shapefiles, but that doesn't concern us here (a shapefile is comprise of several different files, so we leave off the extensions) and we just tell 'readOGR()' where our data is and what the name of the file is. We'll also show a plot of what we're working with as well as miscellaneous functions to help us tell us what we're working with.
</div>
```{r}
require(rgdal)

soils = readOGR(
    dsn="../data",
    layer="soilsData"
)

plot(soils, main="Soils from Western WI")

## Diagnostic functions
class(soils)
### Take a peak here at the top of our attribute table
head(soils@data)
## Make sure not to call head() on the spatial object, as this spits out the 
##    first six features and all their attributes
# head(soils)
## str() not too helpful here as it spits out the guts of the spatial components
# str(soils) 
## Number of features
length(soils)

## index the first feature with a slice
soils[1,]
```
You can see that as we read it in, R tells us how many features, how many soil polygons, are in the data we just read in and how many fields are in the attribute table. Shapefiles are the most common non-database format for spatial data, but later we will cover working with a table of points.

## Structure
## Working with Vector Data

# Raster Data

## Intro
## Input/Output
## Structure
## Working with Raster Data

# Flyover of Coordinate Reference Systems

## A Necessary Evil
Here we'll discuss the situation where you will read in a table of points, that does not have any spatial reference system attached to it.


